version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest


jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies ðŸ“¦
          command: yarn

      - run:
          name: Bootstrapping the Lerna workspace ðŸ§°
          command: yarn bootstrap

      - run:
          name: Lint the source code ðŸ•µðŸ»â€â™‚ï¸
          command: yarn lint

      - run:
          name: Build the application ðŸ‘·ðŸ¼â€â™€ï¸
          command: yarn build

      - run: yarn lerna run --scope=@sketchmine/app-builder test
      - run: yarn lerna run --scope=@sketchmine/code-analyzer test
      - run: yarn lerna run --scope=@sketchmine/dom-agent test
      - run: yarn lerna run --scope=@sketchmine/helpers test
      - run: yarn lerna run --scope=@sketchmine/node-helpers test
      - run: yarn lerna run --scope=@sketchmine/sketch-builder test
      - run: yarn lerna run --scope=@sketchmine/sketch-color-replacer test
      - run: yarn lerna run --scope=@sketchmine/sketch-file-builder test
      - run: yarn lerna run --scope=@sketchmine/sketch-file-format test
      - run: yarn lerna run --scope=@sketchmine/sketch-svg-parser test
      - run: yarn lerna run --scope=@sketchmine/sketch-validation-interface test
      - run: yarn lerna run --scope=@sketchmine/sketch-validation-plugin test
      - run: yarn lerna run --scope=@sketchmine/sketch-validator-nodejs-wrapper test
      - run: yarn lerna run --scope=@sketchmine/sketch-validator test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

  # test:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/repo


  # test-only-changed:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/repo

  #     - run:
  #         name: Run all the tests ðŸ§™ðŸ»â€â™‚ï¸
  #         command: |
  #           changed_packages="$(npx lerna changed | grep "@sketchmine" | paste -sd "," -)"
  #           yarn lerna run --scope={${changed_packages}} test

  # deploy:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/repo

  #     - run:
  #         name: Deploy
  #         command: echo "should deploy!"

workflows:
  version: 2
  build-test:
    jobs:
      - build
      # - test:
      #     requires:
      #       - build
      # - deploy:
      #     requires:
      #       - test
